// Mocks generated by Mockito 5.4.6 from annotations
// in qstory/test/features/qr_operations/presentation/pages/qr_generator_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mobx/mobx.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:qstory/features/qr_operations/data/models/qr_content_model.dart'
    as _i4;
import 'package:qstory/features/qr_operations/data/models/qr_data_model.dart'
    as _i5;
import 'package:qstory/features/qr_operations/presentation/stores/qr_store.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeObservableList_0<T> extends _i1.SmartFake
    implements _i2.ObservableList<T> {
  _FakeObservableList_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReactiveContext_1 extends _i1.SmartFake
    implements _i2.ReactiveContext {
  _FakeReactiveContext_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QrStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockQrStore extends _i1.Mock implements _i3.QrStore {
  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.ObservableList<String> get scanHistory => (super.noSuchMethod(
        Invocation.getter(#scanHistory),
        returnValue: _FakeObservableList_0<String>(
          this,
          Invocation.getter(#scanHistory),
        ),
        returnValueForMissingStub: _FakeObservableList_0<String>(
          this,
          Invocation.getter(#scanHistory),
        ),
      ) as _i2.ObservableList<String>);

  @override
  set generatedData(String? value) => super.noSuchMethod(
        Invocation.setter(
          #generatedData,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastScannedData(String? value) => super.noSuchMethod(
        Invocation.setter(
          #lastScannedData,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastScannedContent(_i4.QrContentModel? value) => super.noSuchMethod(
        Invocation.setter(
          #lastScannedContent,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set scannedPlaceData(_i5.QrDataModel? value) => super.noSuchMethod(
        Invocation.setter(
          #scannedPlaceData,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set pendingQrCodeId(String? value) => super.noSuchMethod(
        Invocation.setter(
          #pendingQrCodeId,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set errorMessage(String? value) => super.noSuchMethod(
        Invocation.setter(
          #errorMessage,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set scanHistory(_i2.ObservableList<String>? value) => super.noSuchMethod(
        Invocation.setter(
          #scanHistory,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_1(
          this,
          Invocation.getter(#context),
        ),
        returnValueForMissingStub: _FakeReactiveContext_1(
          this,
          Invocation.getter(#context),
        ),
      ) as _i2.ReactiveContext);

  @override
  void setGeneratedData(String? data) => super.noSuchMethod(
        Invocation.method(
          #setGeneratedData,
          [data],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> onScan(String? data) => (super.noSuchMethod(
        Invocation.method(
          #onScan,
          [data],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> fetchPlaceInfo(String? qrCode) => (super.noSuchMethod(
        Invocation.method(
          #fetchPlaceInfo,
          [qrCode],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void clearPendingQrCode() => super.noSuchMethod(
        Invocation.method(
          #clearPendingQrCode,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearScannedPlaceData() => super.noSuchMethod(
        Invocation.method(
          #clearScannedPlaceData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearLastScannedData() => super.noSuchMethod(
        Invocation.method(
          #clearLastScannedData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onManualInput(String? input) => super.noSuchMethod(
        Invocation.method(
          #onManualInput,
          [input],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> saveScanStatistics(
    String? qrCodeId,
    String? placeTitle,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveScanStatistics,
          [
            qrCodeId,
            placeTitle,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> getTotalScans() => (super.noSuchMethod(
        Invocation.method(
          #getTotalScans,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
        returnValueForMissingStub: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> hasScanned(String? qrCodeId) => (super.noSuchMethod(
        Invocation.method(
          #hasScanned,
          [qrCodeId],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> markMarkerAsCompleted(String? markerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMarkerAsCompleted,
          [markerId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isMarkerCompleted(String? markerId) => (super.noSuchMethod(
        Invocation.method(
          #isMarkerCompleted,
          [markerId],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}
