// Mocks generated by Mockito 5.4.6 from annotations
// in qstory/test/features/history/presentation/pages/main_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mobx/mobx.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:qstory/features/history/domain/entities/history_entity.dart'
    as _i4;
import 'package:qstory/features/history/presentation/stores/history_store.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeReactiveContext_0 extends _i1.SmartFake
    implements _i2.ReactiveContext {
  _FakeReactiveContext_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HistoryStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryStore extends _i1.Mock implements _i3.HistoryStore {
  @override
  List<_i4.HistoryEntity> get historyList => (super.noSuchMethod(
        Invocation.getter(#historyList),
        returnValue: <_i4.HistoryEntity>[],
        returnValueForMissingStub: <_i4.HistoryEntity>[],
      ) as List<_i4.HistoryEntity>);

  @override
  List<_i4.HistoryEntity> get filteredList => (super.noSuchMethod(
        Invocation.getter(#filteredList),
        returnValue: <_i4.HistoryEntity>[],
        returnValueForMissingStub: <_i4.HistoryEntity>[],
      ) as List<_i4.HistoryEntity>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set historyList(List<_i4.HistoryEntity>? value) => super.noSuchMethod(
        Invocation.setter(
          #historyList,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set filteredList(List<_i4.HistoryEntity>? value) => super.noSuchMethod(
        Invocation.setter(
          #filteredList,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set errorMessage(String? value) => super.noSuchMethod(
        Invocation.setter(
          #errorMessage,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_0(
          this,
          Invocation.getter(#context),
        ),
        returnValueForMissingStub: _FakeReactiveContext_0(
          this,
          Invocation.getter(#context),
        ),
      ) as _i2.ReactiveContext);

  @override
  _i5.Future<void> loadHistory() => (super.noSuchMethod(
        Invocation.method(
          #loadHistory,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void filterHistory(String? query) => super.noSuchMethod(
        Invocation.method(
          #filterHistory,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> addHistoryItem(_i4.HistoryEntity? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #addHistoryItem,
          [item],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
